server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates: 
            - Path=/api/customer/**
        - id: product-service
          uri: lb://product-service
          predicates: 
            - Path=/api/product/**
          filters:
            - StripPrefix=2
        - id: bank-service
          uri: lb://bank-service
          predicates: 
            - Path=/api/bank/**
          filters:
            - StripPrefix=2
        - id: account-service
          uri: lb://account-service
          predicates: 
            - Path=/api/account/**
          filters:
            - StripPrefix=2
        - id: credits-service
          uri: lb://credits-service
          predicates: 
            - Path=/api/credit/**
          filters:
            - StripPrefix=2        
        - id: transaction-service
          uri: lb://transaction-service
          predicates: 
            - Path=/api/transaction/**
          filters:
            - StripPrefix=2