server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6  # numero de llamadas
        failure-rate-threshold: 50 #umbral de fallos
        wait-duration-in-open-state: 20s  #tiempo de espera en estado abierto
        permitted-number-of-calls-in-half-open-state: 4 #numero de llamadas en estado abierto
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      customerCircuitBreaker:
        base-config: defecto
      productCircuitBreaker:
        base-config: defecto
      accountCircuitBreaker:
        base-config: defecto
      creditCircuitBreaker:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 2s
    instances:
      customerFindById:
        base-config: defecto
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates: 
            - Path=/api/customer/**
          filters:
            - name: CircuitBreaker
              args : 
                name: customerCircuitBreaker
                statusCodes: 500
                fallbackUri: forward:/fallback/customers
        - id: product-service
          uri: lb://product-service
          predicates: 
            - Path=/api/product/**
          filters:
            - name: CircuitBreaker
              args : 
                name: productCircuitBreaker
                statusCodes: 500
                fallbackUri: forward:/fallback/products
        - id: bank-service
          uri: lb://bank-service
          predicates: 
            - Path=/api/bank/**
        - id: account-service
          uri: lb://account-service
          predicates: 
            - Path=/api/account/**
          filters:
            - name: CircuitBreaker
              args : 
                name: accountCircuitBreaker
                statusCodes: 500
                fallbackUri: forward:/fallback/accounts
        - id: credit-service
          uri: lb://credit-service
          predicates: 
            - Path=/api/credit/**
          filters:
            - name: CircuitBreaker
              args : 
                name: creditCircuitBreaker
                statusCodes: 500
                fallbackUri: forward:/fallback/credits
        - id: transaction-service
          uri: lb://transaction-service
          predicates: 
            - Path=/api/transaction/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/report/**