server:
  port: 8085
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: EhsBanksDB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/