server:
  port: 8087
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: EhsBankCreditDB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
