server:
  port: ${PORT:0} #8087
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: EhsBankCreditDB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}