server:
  port: ${PORT:0} #8081
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: EhsCustomerDB
eureka:
  client:
    service-url:
#      defaultZone: http://eureka-server:8761/eureka
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}